
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."Crawler" (
    "id" bigint NOT NULL,
    "last_crawl_timestamp" bigint DEFAULT '1672502400000'::bigint NOT NULL
);

ALTER TABLE "public"."Crawler" OWNER TO "postgres";

ALTER TABLE "public"."Crawler" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Crawler_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Game" (
    "id" bigint NOT NULL,
    "name" "text",
    "platform" "text",
    "search_count" bigint DEFAULT '0'::bigint,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."Game" OWNER TO "postgres";

ALTER TABLE "public"."Game" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Game_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Price" (
    "id" bigint NOT NULL,
    "game_id" bigint,
    "ptt_article_id" "text",
    "price" integer,
    "condition" smallint,
    "trade_type" smallint,
    "posted_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE "public"."Price" OWNER TO "postgres";

ALTER TABLE "public"."Price" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Price_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."Crawler"
    ADD CONSTRAINT "Crawler_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Game"
    ADD CONSTRAINT "Game_pkey1" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Price"
    ADD CONSTRAINT "Price_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Price"
    ADD CONSTRAINT "Price_ptt_article_id_key" UNIQUE ("ptt_article_id");

ALTER TABLE "public"."Crawler" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."Price" FOR SELECT USING (true);

ALTER TABLE "public"."Game" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Price" ENABLE ROW LEVEL SECURITY;

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."Crawler" TO "anon";
GRANT ALL ON TABLE "public"."Crawler" TO "authenticated";
GRANT ALL ON TABLE "public"."Crawler" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Crawler_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Crawler_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Crawler_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Game" TO "anon";
GRANT ALL ON TABLE "public"."Game" TO "authenticated";
GRANT ALL ON TABLE "public"."Game" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Game_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."Game_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Game_id_seq1" TO "service_role";

GRANT ALL ON TABLE "public"."Price" TO "anon";
GRANT ALL ON TABLE "public"."Price" TO "authenticated";
GRANT ALL ON TABLE "public"."Price" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Price_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Price_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Price_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
